# baseline_data.py

EXP_CLOUD_ERRORS = [
    # --- SECTION 1: EXPERIENCEBUNDLE & STRUCTURE ---
    {"category": "ExperienceBundle", "error": "ExperienceBundle isn't enabled for Aura sites.", "resolution": "In the target org, go to Digital Experiences > Settings and check 'Enable ExperienceBundle Metadata API'."},
    {"category": "ExperienceBundle", "error": "The viewType value in views and routeType in routes must match.", "resolution": "A mismatch exists between the view and route JSON files. Ensure both reference the same type (e.g., 'comm__live_object')."},
    {"category": "ExperienceBundle", "error": "The activeViewId for the Route doesn't point to a valid view.", "resolution": "A view was deleted but the route still references it. Update the 'activeViewId' in the routes/[page].json file."},
    {"category": "ExperienceBundle", "error": "The currentThemeId property is null or points to a non-theme component.", "resolution": "The theme ID doesn't exist in the target. Update the 'currentThemeId' in the site's main JSON config to a valid ID."},
    {"category": "ExperienceBundle", "error": "Content file name is invalid. Must be content.json or localeName.json.", "resolution": "Remove auto-generated 'mobile.json' or 'tablet.json' files from the repository as they are rejected during deployment."},
    {"category": "ExperienceBundle", "error": "The appPageId in both files must point to the same SPA.", "resolution": "Ensure the view and route are correctly mapped to the same Single Page Application (SPA) configuration."},
    {"category": "ExperienceBundle", "error": "The activeViewId for the route [Name] doesn't point to a valid view.", "resolution": "Verify the activeViewId in the route JSON matches an existing id in the views folder."},
    {"category": "ExperienceBundle", "error": "Property [Name] is not valid for the current template.", "resolution": "You are trying to deploy an Aura property to an LWR site (or vice-versa)."},
    {"category": "ExperienceBundle", "error": "Java.lang.IndexOutOfBoundsException during Change Set.", "resolution": "Common Change Set bug; deploy via SFDX/VS Code Metadata API instead."},
    {"category": "ExperienceBundle", "error": "The page [Name] is missing a required layout.", "resolution": "Ensure the layout metadata file for that specific page variation is included in the package."},
    {"category": "ExperienceBundle", "error": "Component [ID] not found in the target org.", "resolution": "Ensure the Managed Package containing the custom component is installed in the target."},
    {"category": "ExperienceBundle", "error": "Invalid IOS/Android URL in Mobile Publisher settings.", "resolution": "Remove placeholder store URLs in the source metadata before deploying."},
    {"category": "ExperienceBundle", "error": "The site's primary language [Code] is not supported.", "resolution": "Add the required language to the 'Available Languages' in the target org's Site Settings."},
    {"category": "ExperienceBundle", "error": "Site Component Label: data value too large.", "resolution": "Shorten the Page Variation name (limit is usually 80 characters)."},
    {"category": "ExperienceBundle", "error": "Route [Name] has a duplicate path.", "resolution": "Two pages are trying to use the same URL slug (e.g., /home)."},
    {"category": "ExperienceBundle", "error": "attribute [layoutType]: Attribute value is not valid.", "resolution": "Check if a component's integer value (like '1') needs to be a string ('1 Column')."},
    {"category": "ExperienceBundle", "error": "The branding set [ID] is not found.", "resolution": "Include the BrandingSet metadata associated with the site theme."},
    {"category": "ExperienceBundle", "error": "Cannot change the Template of an existing site.", "resolution": "You cannot 'overwrite' a site template. Delete the target site or create a new one."},
    {"category": "ExperienceBundle", "error": "Template [Name] version is no longer supported.", "resolution": "Update the site template version in the source org before retrieving metadata."},
    {"category": "ExperienceBundle", "error": "The search results page reference is missing.", "resolution": "Link the Search component to a valid view ID in the JSON metadata."},
    {"category": "ExperienceBundle", "error": "The developer name [Name] is already in use.", "resolution": "A page or component shares a name with a deleted item in the Recycle Bin."},
    {"category": "ExperienceBundle", "error": "API version [Number] is too low for ExperienceBundle.", "resolution": "Update package.xml to at least version 48.0."},
    {"category": "ExperienceBundle", "error": "ConcurrentEditDetectedException.", "resolution": "A server-side lock; wait 10 minutes and retry the deployment."},
    {"category": "ExperienceBundle", "error": "Attribute [quickActionName] is missing a value.", "resolution": "Ensure the referenced Global Action exists in the target org."},
    {"category": "ExperienceBundle", "error": "Default Web Address must be alphanumeric.", "resolution": "Check urlPathPrefix for trailing slashes or hyphens."},
    {"category": "ExperienceBundle", "error": "The view [Name] is not available for the Guest User.", "resolution": "Check the Page Access property in the metadata JSON."},
    {"category": "ExperienceBundle", "error": "Missing 'forceCommunity:availableForAllPageTypes' interface.", "resolution": "Add the interface to the Aura component's .cmp file."},
    {"category": "ExperienceBundle", "error": "Mobile.json file causing content length errors.", "resolution": "Use .forceignore to exclude auto-generated mobile metadata if not needed."},
    {"category": "ExperienceBundle", "error": "navigationMenuEditorRefresh: Navigation Menu API name doesn't exist.", "resolution": "A component references a renamed menu. Remove the 'navigationMenuEditorRefresh' line from JSON and re-assign manually."},

    # --- SECTION 2: NETWORK & MEMBERSHIP ---
    {"category": "Network", "error": "In field: Network - no Network named [Name] found.", "resolution": "The Network metadata is missing or named incorrectly. Ensure the Network and CustomSite are included in the same deployment package."},
    {"category": "Network", "error": "no NavigationMenu named [Menu_Name] found.", "resolution": "The Navigation Menu is missing from the package. Add the 'NavigationMenu' metadata type to your package.xml."},
    {"category": "Network", "error": "Cannot create a new component with the namespace: SFDC_Default_...", "resolution": "You are trying to deploy a system-managed menu. Rename the menu to a custom name without the 'SFDC_Default' prefix."},
    {"category": "Network", "error": "Site.com site [ID] is associated with another experience.", "resolution": "The Network is already tied to a different site. Disassociate the old site or create a unique Network name."},
    {"category": "Network", "error": "Member profile [Name] was not found.", "resolution": "Deploy the Profile or ensure it exists in the target org before site membership assignment."},
    {"category": "Network", "error": "Self-registration is not enabled for this network.", "resolution": "Check the 'Allow external users to self-register' checkbox in the target org."},
    {"category": "Network", "error": "Default account for guest users is required.", "resolution": "Set a default account in the Digital Experience settings for the guest user."},
    {"category": "Network", "error": "The welcome email template [Name] does not exist.", "resolution": "Deploy the referenced EmailTemplate metadata."},
    {"category": "Network", "error": "Profile [Name] does not have access to the site.", "resolution": "Add the profile to the Site Members list in Administration settings."},
    {"category": "Network", "error": "Network membership exceeds the limit.", "resolution": "Review license counts or remove inactive profiles from the site."},
    {"category": "Network", "error": "Permission Set [Name] not found for site assignment.", "resolution": "Include the Permission Set in your deployment package."},
    {"category": "Network", "error": "Cannot deploy Network while site is in 'Live' status.", "resolution": "Usually a transient error; try deploying to a sandbox first."},
    {"category": "Network", "error": "ForgotPassword email template is missing.", "resolution": "Ensure the template is in the email/ folder of your metadata."},
    {"category": "Network", "error": "The guest user profile is not visible.", "resolution": "Sites must be 'Enabled' before the Guest Profile metadata can be fully updated."},
    {"category": "Network", "error": "Invalid Login Page type.", "resolution": "Check if the site is using a custom Visualforce login page that wasn't deployed."},
    {"category": "Network", "error": "External users cannot be assigned to this profile.", "resolution": "Change the Profile's 'User Type' to 'CspLitePortal' or similar."},
    {"category": "Network", "error": "The custom domain [Name] is not verified.", "resolution": "Set up the Domain and Certificate in the target org before deploying the Site."},
    {"category": "Network", "error": "Login Discovery handler not found.", "resolution": "Deploy the Apex class used for Login Discovery."},
    {"category": "Network", "error": "The site's certificate has expired.", "resolution": "Update the certificate in the target org's 'Certificate and Key Management.'"},
    {"category": "Network", "error": "IP Range restriction blocking deployment.", "resolution": "Add the deployment user's IP to the Network's trusted ranges."},
    {"category": "Network", "error": "Two-factor authentication requirement mismatch.", "resolution": "Check Profile/Permission Set session security settings."},
    {"category": "Network", "error": "Site path is already taken.", "resolution": "Change the urlPathPrefix or rename the existing site."},
    {"category": "Network", "error": "Max number of sites (100) reached.", "resolution": "Delete unused sites or request a limit increase from Salesforce."},
    {"category": "Network", "error": "User visibility settings preventing membership.", "resolution": "Enable 'Community User Visibility' in Sharing Settings."},
    {"category": "Network", "error": "The network ID is hardcoded in a component.", "resolution": "Replace hardcoded IDs with the $Network.id global variable."},
    {"category": "Network", "error": "Profile [Name] does not have 'API Enabled' permission.", "resolution": "Enable API access for the user profile performing the deployment."},
    {"category": "Network", "error": "Site administrator must have a standard profile.", "resolution": "Ensure the user creating/deploying the site isn't using a portal license."},
    {"category": "Network", "error": "Email verification required for new members.", "resolution": "Check 'Email Verification' settings in the Network metadata."},

    # --- SECTION 3: CMS & ASSETS ---
    {"category": "CMS", "error": "Navigation menu [Name] not found.", "resolution": "Include the NavigationMenu metadata in the deployment package."},
    {"category": "CMS", "error": "Managed Content (CMS) not found for ID [ID].", "resolution": "Use the 'Export/Import' feature in CMS Workspace; CMS content doesn't deploy via Metadata API."},
    {"category": "CMS", "error": "Asset file [Name] not found.", "resolution": "Include the ContentAsset metadata for images/logos."},
    {"category": "CMS", "error": "The menu item [Name] points to a deleted page.", "resolution": "Update the Navigation Menu in the source org to point to active pages."},
    {"category": "CMS", "error": "CMS Channel [Name] is not active.", "resolution": "Manually create and associate the channel in the target org."},
    {"category": "CMS", "error": "Maximum number of navigation items exceeded.", "resolution": "Limit your menu to 10-15 top-level items."},
    {"category": "CMS", "error": "Library [Name] is not accessible to site users.", "resolution": "Update the Content Library permissions in the target org."},
    {"category": "CMS", "error": "The logo asset ID is null.", "resolution": "Re-upload the site logo in the Builder and re-retrieve the metadata."},
    {"category": "CMS", "error": "Rich Text component contains a broken image link.", "resolution": "Ensure images are stored as Assets, not hardcoded external URLs."},
    {"category": "CMS", "error": "The CMS Workspace is not associated with the site.", "resolution": "Manually link the CMS Workspace to the site in the target org."},
    {"category": "CMS", "error": "Topic [Name] was not found.", "resolution": "Deploy ManagedTopic metadata or create topics manually."},
    {"category": "CMS", "error": "Navigation Menu Item type 'System' is invalid.", "resolution": "Check for deprecated menu items (like 'Messages' in some templates)."},
    {"category": "CMS", "error": "External URL in menu is missing 'https://'.", "resolution": "Fix the URL formatting in the Navigation Menu metadata."},
    {"category": "CMS", "error": "Asset file name contains illegal characters.", "resolution": "Rename the file to use only alphanumeric characters."},
    {"category": "CMS", "error": "The CMS Content Type [Name] is missing.", "resolution": "Deploy the ManagedContentType metadata."},
    {"category": "CMS", "error": "Navigation Menu ID mismatch.", "resolution": "Use the API name in the code instead of the 18-digit ID."},
    {"category": "CMS", "error": "Branding Set logo doesn't render after deployment.", "resolution": "Re-link the Asset File in the target org's Branding Editor."},
    {"category": "CMS", "error": "CMS Search is not returning results.", "resolution": "Enable the 'Public' checkbox on the CMS Channel."},
    {"category": "CMS", "error": "Asset file is in 'Draft' status.", "resolution": "Publish the asset file before retrieving for deployment."},
    {"category": "CMS", "error": "The menu 'Default Navigation' cannot be deleted.", "resolution": "Do not remove the default menu from the metadata bundle."},
    {"category": "CMS", "error": "CMS Content is not localized for [Language].", "resolution": "Ensure translations exist in CMS for all site languages."},
    {"category": "CMS", "error": "The footer component is missing an asset.", "resolution": "Check the BrandingSet or ContentAsset for the footer logo."},
    {"category": "CMS", "error": "CMS Collections not appearing.", "resolution": "Manually create the collection in the target CMS Workspace."},
    {"category": "CMS", "error": "Navigation Menu label cannot be blank.", "resolution": "Ensure all items in the .navigationMenu-meta.xml have a label."},

    # --- SECTION 4: APEX & OBJECT ACCESS ---
    {"category": "Apex", "error": "Apex Class [Name] not found.", "resolution": "Deploy the Apex controller used by custom components."},
    {"category": "Apex", "error": "Field [Name] is not visible to the Guest User.", "resolution": "Update the Guest User Profile's Field Level Security (FLS)."},
    {"category": "Apex", "error": "Standard Object [Name] access denied.", "resolution": "Enable object permissions in the Guest/Member profile."},
    {"category": "Apex", "error": "The Apex controller must use 'with sharing' for security.", "resolution": "Update the Apex class definition to ensure data security."},
    {"category": "Apex", "error": "Record Type [Name] not found for Object [Name].", "resolution": "Deploy the Record Type metadata."},
    {"category": "Apex", "error": "Validation Rule failed on site user creation.", "resolution": "Bypass the validation rule for the Guest User Profile."},
    {"category": "Apex", "error": "The flow [Name] is not active.", "resolution": "Manually activate the Flow in the target org after deployment."},
    {"category": "Apex", "error": "Custom Metadata [Name] not accessible.", "resolution": "Add Custom Metadata access to the Site Profile."},
    {"category": "Apex", "error": "System.QueryException: List has no rows for assignment.", "resolution": "The component is querying data that doesn't exist in the target org."},
    {"category": "Apex", "error": "Flow input variable [Name] is missing.", "resolution": "Ensure the component passing variables to the Flow is updated."},
    {"category": "Apex", "error": "Apex sharing reason not found.", "resolution": "Deploy the SharingReason metadata for the object."},
    {"category": "Apex", "error": "The 'runAs' user is inactive.", "resolution": "Ensure the site owner/admin user is active in the target org."},
    {"category": "Apex", "error": "LWC Component error: [Name] is not defined.", "resolution": "Fix the JavaScript import in your custom LWC."},
    {"category": "Apex", "error": "Apex trigger preventing site user login.", "resolution": "Review User object triggers for Experience Cloud compatibility."},
    {"category": "Apex", "error": "The object [Name] is not supported in LWR.", "resolution": "Some standard objects are Aura-only; use Apex for LWR data binding."},
    {"category": "Apex", "error": "Named Credential [Name] not found.", "resolution": "Deploy the Named Credential used for external API calls."},
    {"category": "Apex", "error": "The CSP Trusted Site [Name] is missing.", "resolution": "Include CspTrustedSite metadata for external script/API access."},
    {"category": "Apex", "error": "JavaScript Heap out of memory (Builder).", "resolution": "Too many components on one page; use 'Page Variations' to split content."},
    {"category": "Apex", "error": "Cross-Origin Resource Sharing (CORS) error.", "resolution": "Add the site URL to the CORS settings in the target org."},
    {"category": "Apex", "error": "The Apex action is not marked '@AuraEnabled'.", "resolution": "Add the annotation to the Apex method."},
    {"category": "Apex", "error": "Governor Limit: Too many SOQL queries (Site Login).", "resolution": "Optimize the Login Discovery handler or custom login controller."},
    {"category": "Apex", "error": "Object [Name] is in a Managed Package not installed.", "resolution": "Install the package before deploying dependent site metadata."},
    {"category": "Apex", "error": "The site's global header is missing.", "resolution": "Ensure the 'Theme Layout' is correctly assigned in the Builder."},
    {"category": "Apex", "error": "External Object [Name] not found.", "resolution": "Set up Salesforce Connect/External Data Source in the target org."},
    {"category": "Apex", "error": "Static Resource [Name] not found.", "resolution": "Deploy the StaticResource used for CSS or JS libraries."},

    # --- SECTION 5: GENERAL ---
    {"category": "General", "error": "In field: siteAdmin - no User named [Email] found.", "resolution": "The site admin user in the source org doesn't exist in the target. Update the .site file to a valid username in the target org."},
    {"category": "General", "error": "The value for urlPathPrefix in ExperienceBundle isn't valid.", "resolution": "Check for illegal characters or trailing slashes in the urlPathPrefix field within the CustomSite or Network XML."},
    {"category": "General", "error": "Not available for deploy for this organization.", "resolution": "Digital Experiences are not enabled in the target org. Enable them under Digital Experiences > Settings."},
    {"category": "General", "error": "The reportId property references an object with ID value [ID].", "resolution": "Hardcoded IDs fail across orgs. Use a script to replace source IDs with target IDs before deploying."},
    {"category": "General", "error": "In field: indexPage - no ApexPage named CommunitiesLanding found.", "resolution": "Standard Visualforce pages are missing. Include 'ApexPage' components for Login and Landing in your deployment."},
    {"category": "General", "error": "Attribute [quickActionName]: Attribute is required and missing a value.", "resolution": "A component references a Quick Action that is empty or missing. Ensure the action exists in the target org."},
    {"category": "General", "error": "Too many retries of batch save in the presence of Apex triggers.", "resolution": "Deployment timeout. Break the deployment into smaller chunks: Network first, then ExperienceBundle."},
    {"category": "General", "error": "Property 'namesegment' not valid in version [XX.0].", "resolution": "API Version mismatch. Update the package.xml version to match the source metadata API version."},
    {"category": "General", "error": "Unexpected error occurred during ExperienceBundle deployment.", "resolution": "Usually a Salesforce release mismatch. Try deploying with the '--ignore-warnings' flag."}
]